#!/bin/bash
# exit when something errors
set -e

#run the hidden test cases
echo "RUNNING INTSRUCTOR TEST CASES"
curl -o sorts_acceptance_tests.py https://raw.githubusercontent.com/jjohn163/example/main/Labs/Lab05/soln/binary_search_tree_acceptance_tests.py
echo "RUNNING SORTS TESTS"
timeout 5 python3 sorts_acceptance_tests.py

echo "TESTING COMPLETE"
