#!/bin/bash

# exit when something errors
set -e

# run the student tests
echo "RUNNING STUDENT TEST CASES"
python3 planets_tests.py

#run coverage, will fail and kill the script if coverage is less than 100%
echo "RUNNING CODE COVERAGE"
python3 -m coverage run -m unittest planets_tests.py; python3 -m coverage report -m --fail-under=100

#run the hidden test cases
echo "RUNNING INTSRUCTOR TEST CASES"
curl -H 'Authorization: token e3bbdd2745bb74f81340e5c4e0fb806345cb5c8e' -o lab1_testcases.py https://raw.githubusercontent.com/jjohn163/CPE202_TestCases/main/lab1_testcases.py; python3 lab1_testcases.py

echo "TESTING COMPLETE"
