#!/bin/bash

# exit when something errors
set -e

#run coverage, will fail and kill the script if coverage is less than 100%
echo "RUNNING STUDENT TEST CASES AND CODE COVERAGE"
python3 -m coverage run -a -m unittest stack_tests.py
python3 -m coverage report -m --fail-under=100 --omit=stack_tests.py,stack_linked.py

#run the hidden test cases
echo "RUNNING INTSRUCTOR TEST CASES"
curl -H 'Authorization: token 6ff6f7940db55594ffbd1a3e4b29305e9a590031' -o stack_array_acceptance_tests.py https://raw.githubusercontent.com/jjohn163/CPE202_TestCases/main/Labs/Lab02/soln/stack_array_acceptance_tests.py
timeout 11 python3 stack_array_acceptance_tests.py
curl -H 'Authorization: token 6ff6f7940db55594ffbd1a3e4b29305e9a590031' -o stack_linked_acceptance_tests.py https://raw.githubusercontent.com/jjohn163/CPE202_TestCases/main/Labs/Lab02/soln/stack_linked_acceptance_tests%20.py
timeout 11 python3 stack_linked_acceptance_tests.py

echo "TESTING COMPLETE"
