#!/bin/bash

# exit when something errors
set -e

#run coverage, will fail and kill the script if coverage is less than 100%
echo "RUNNING STUDENT TEST CASES AND CODE COVERAGE"
python3 -m coverage run -a -m unittest stack_tests.py
python3 -m coverage report -m --fail-under=100 --omit=stack_tests.py,stack_linked.py

#run the hidden test cases
echo "RUNNING INTSRUCTOR TEST CASES"
curl -H 'Authorization: token e3bbdd2745bb74f81340e5c4e0fb806345cb5c8e' -o stack_array_acceptance_tests.py https://raw.githubusercontent.com/jjohn163/CPE202_TestCases/main/Labs/Lab02/soln/stack_array_acceptance_tests.py
timeout 11 --signal='TESTS TIMED OUT' python3 stack_array_acceptance_tests.py
curl -H 'Authorization: token e3bbdd2745bb74f81340e5c4e0fb806345cb5c8e' -o stack_linked_acceptance_tests.py https://raw.githubusercontent.com/jjohn163/CPE202_TestCases/main/Labs/Lab02/soln/stack_linked_acceptance_tests%20.py
timeout 11 --signal='TESTS TIMED OUT' python3 stack_linked_acceptance_tests.py

echo "TESTING COMPLETE"
