#!/bin/bash

# exit when something errors
set -e

echo "RUNNING STUDENT TEST CASES"
python3 -m coverage run -a -m unittest hash_quad_tests.py
python3 -m coverage report -m --fail-under=100 --omit=hash_quad_tests.py,concordance.py,concordance_tests.py

#run the hidden test cases
echo "DOWNLOADING FILES FOR TESTS"
curl -o declaration.txt https://raw.githubusercontent.com/jjohn163/example/main/Projects/Assignment%204/soln/declaration.txt
curl -o declaration_sol.txt https://raw.githubusercontent.com/jjohn163/example/main/Projects/Assignment%204/soln/declaration_sol.txt
curl -o file1.txt https://raw.githubusercontent.com/jjohn163/example/main/Projects/Assignment%204/soln/file1.txt
curl -o file1_sol.txt https://raw.githubusercontent.com/jjohn163/example/main/Projects/Assignment%204/soln/file1_sol.txt
curl -o file2.txt https://raw.githubusercontent.com/jjohn163/example/main/Projects/Assignment%204/soln/file2.txt
curl -o file2_sol.txt https://raw.githubusercontent.com/jjohn163/example/main/Projects/Assignment%204/soln/file2_sol.txt
curl -o dictionary_a-c.txt https://raw.githubusercontent.com/jjohn163/example/main/Projects/Assignment%204/soln/dictionary_a-c.txt
curl -o dictionary_a-c_sol.txt https://raw.githubusercontent.com/jjohn163/example/main/Projects/Assignment%204/soln/dictionary_a-c_sol.txt
curl -o stop_words.txt https://raw.githubusercontent.com/jjohn163/example/main/Projects/Assignment%204/soln/stop_words.txt
curl -o stop_words_sol.txt https://raw.githubusercontent.com/jjohn163/example/main/Projects/Assignment%204/soln/stop_words_sol.txt
sleep 5
echo "RUNNING INTSRUCTOR TEST CASES"
curl -o hash_quad_acceptance_tests.py https://raw.githubusercontent.com/jjohn163/example/main/Projects/Assignment%204/soln/hash_quad_acceptance_tests.py
timeout 10 python3 hash_quad_acceptance_tests.py
curl -o concordance_acceptance_tests.py https://raw.githubusercontent.com/jjohn163/example/main/Projects/Assignment%204/soln/concordance_acceptance_tests.py
timeout 10 python3 concordance_acceptance_tests.py


echo "TESTING COMPLETE"
