#!/bin/bash

# exit when something errors
set -e

#run coverage, will fail and kill the script if coverage is less than 100%
echo "RUNNING STUDENT TEST CASES AND CODE COVERAGE"
python3 -m coverage run -a -m unittest stack_tests.py
python3 -m coverage report -m --fail-under=100 --omit=queue_tests.py,queue_linked.py

#run the hidden test cases
echo "RUNNING INTSRUCTOR TEST CASES"

curl -o queue_array_acceptance_tests.py https://raw.githubusercontent.com/jjohn163/example/main/Labs/Lab03/soln/queue_array_acceptance_tests.py
echo "RUNNING QUEUE ARRAY TESTS"
timeout 8 python3 queue_array_acceptance_tests.py

curl -o queue_linked_acceptance_tests.py https://raw.githubusercontent.com/jjohn163/example/main/Labs/Lab03/soln/queue_linked_acceptance_tests.py
echo "RUNNING QUEUE LINKED TESTS"
timeout 8 python3 queue_linked_acceptance_tests.py

echo "TESTING COMPLETE"
