#!/bin/bash

# exit when something errors
set -e

#run coverage, will fail and kill the script if coverage is less than 100%
echo "RUNNING STUDENT TEST CASES AND CODE COVERAGE"
python3 -m coverage run -a -m unittest base_convert_testcases.py
python3 -m coverage run -a -m unittest bears_tests.py
python3 -m coverage run -a -m unittest perm_lex_testcases.py
python3 -m coverage report -m --fail-under=100 --omit=base_convert_testcases.py,bears_tests.py,perm_lex_testcases.py

#run the hidden test cases
echo "RUNNING INTSRUCTOR TEST CASES"
curl -o base_convert_acceptance_tests.py https://raw.githubusercontent.com/jjohn163/example/main/Projects/Assignment%201/soln/base_convert_acceptance_tests.py
echo "RUNNING BASE CONVERT TEST CASES"
python3 base_convert_acceptance_tests.py
curl -o bears_acceptance_tests.py https://raw.githubusercontent.com/jjohn163/example/main/Projects/Assignment%201/soln/bears_acceptance_tests.py
echo "RUNNING BEARS TEST CASES"
python3 bears_acceptance_tests.py
curl -o perm_lex_acceptance_tests.py https://raw.githubusercontent.com/jjohn163/example/main/Projects/Assignment%201/soln/perm_lex_acceptance_tests.py
echo "RUNNING PERM LEX TEST CASES"
python3 perm_lex_acceptance_tests.py

echo "TESTING COMPLETE"
